  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[main]]
  name = "Projects"
  weight = 300
  identifier = "project"
  url = "/projects/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact"